# ==========================
# GEOGRAFÍA
# ==========================
Geografía = [
    {"pregunta": "¿Cuál es la capital de Colombia?", 
     "opcion": ["Bogotá", "Medellín", "Cali", "Barranquilla"], 
     "respuesta": "Bogotá"},
    {"pregunta": "¿En qué continente se encuentra Colombia?", 
     "opcion": ["América", "Europa", "África", "Asia"], 
     "respuesta": "América"},
    {"pregunta": "¿Cuál es el río más largo de Colombia?", 
     "opcion": ["Río Magdalena", "Río Cauca", "Río Sinú", "Río Atrato"], 
     "respuesta": "Río Magdalena"},
    {"pregunta": "¿En qué departamento está el Parque Tayrona?", 
     "opcion": ["Magdalena", "Antioquia", "Atlántico", "Santander"], 
     "respuesta": "Atlántico"},
    {"pregunta": "¿Qué océano se encuentra al occidente de Colombia?", 
     "opcion": ["Océano Pacífico", "Océano Atlántico", "Océano Índico", "Mar Caribe"], 
     "respuesta": "Océano Pacífico"},
    {"pregunta": "¿Cuál es la capital del Valle del Cauca?", 
     "opcion": ["Calí", "Palmira", "Buenaventura", "Argelia"], 
     "respuesta": "Calí"},
    {"pregunta": "¿Dónde está el Desierto de la Tatacoa?", 
     "opcion": ["Huila", "Antioquia", "Atlántico", "Santander"], 
     "respuesta": "Huila"},
    {"pregunta": "¿Qué mar está al norte de Colombia?", 
     "opcion": ["Mar Caribe", "Océano Atlántico", "Océano Pacífico", "Océano Índico"], 
     "respuesta": "Mar Caribe"},
    {"pregunta": "¿Cuál es la montaña costera más alta del mundo?", 
     "opcion": ["Cerro de la Popa", "Cerro del Rodeo", "Cerro de San Juan", "Cerro de la Cruz"], 
     "respuesta": "Cerro de la Popa"},
    {"pregunta": "¿Cómo se llama el sistema montañoso que atraviesa Colombia?", 
     "opcion": ["Cordillera Occidental", "Cordillera Oriental", "Cordillera de los Andes", "Cordillera del Sur"], 
     "respuesta": "Cordillera de los Andes"},
    {"pregunta": "¿Cuántas regiones naturales tiene Colombia en total?", 
     "opcion": ["5", "6", "7", "8"], 
     "respuesta": "6"},
    {"pregunta": "¿Qué deporte ha dado más oros olímpicos a Colombia?", 
     "opcion": ["Ciclimos", "Atletismo", "Levantamiento de pesas", "Boxeo"], 
     "respuesta": "Levantamiento de pesas"},
    {"pregunta": "¿Cuál es la liga FCF?", 
     "opcion": ["La Federación Colombiana de Baloncesto","La Federación Colombiana de Fútbol", "La Federación Colombiana de Atletismo", "La Federación Colombiana de Natación"],
     "respuesta": "La Federación Colombiana de Fútbol"},
]
# ==========================
# CULTURA
# ==========================
Cultura = [
    {"pregunta": "¿Qué flor es símbolo de Colombia?",
     "opcion": ["La Orquidea","La Rosa", "La Margarita", "El Girasol"], 
     "respuesta": "La Orquidea"},
    {"pregunta": "¿Cuál es la danza folclórica más representativa de Colombia?", 
     "opcion": ["El Regueton","La Cumbia","El Vallenato", "El Joropo"], 
     "respuesta": "La Cumbia"},
    {"pregunta": "¿Cuál es el plato típico colombiano más famoso?", 
     "opcion": ["Las arepas","La empanada", "El sancocho", "La bandeja Paisa"], 
     "respuesta": "La bandeja Paisa"},
    {"pregunta": "¿Cuál es el festival más famoso de Colombia?", 
     "opcion": ["El Festival de la Leyenda Vallenata", "El Festival de Música", "El Carnaval de Barranquilla","La Feria de las Flores"], 
     "respuesta": "El Carnaval de Barranquilla"},
    {"pregunta": "¿Cuál es el género musical más famoso de Colombia?", 
     "opcion": ["El Vallenato","El Regueton", "La Cumbia", "El Joropo"], 
     "respuesta": "El Vallenato"},
    {"pregunta": "¿Cómo se llama la bebida típica el cual se hace con panela y limón?", 
     "opcion": ["El agua de panela","El agua de caña", "El jugo de mango", "El refresco de naranja"], 
     "respuesta": "El agua de panela"},
    {"pregunta": "¿Cuál es el instrumento principal de el vallenato?", 
     "opcion": ["El acordeón", "La guitarra", "El tambor", "El piano"], 
     "respuesta": "El acordeón"},
    {"pregunta": "¿Cuál es el dulce típico de Colombia, este se fabrica mayormente en el municipio de Velez-Santander?", 
     "opcion": ["Bocadillo Veleño", "Arequipe", "Chocoramo", "Panelitas de leche"], 
     "respuesta": "Bocadillo Veleño"},
    {"pregunta": "¿Cuál es la artesanía originaria de La Guajira?", 
     "opcion": ["Mochila Wayuu", "Sombrero Vueltiao", "Cestería de Mompox", "Cerámica de Ráquira"], 
     "respuesta": "Mochila Wayuu"},
    {"pregunta": "¿Cómo se hace el Sombrero Vueltiao?", 
     "opcion": ["Se hace con palma de coco y se coloca en la cabeza", "Se hace con palma de cera y se coloca en la cabeza", "Se hace con palma de caña y se coloca en la cabeza", "Se hace con palma de plátano y se coloca en la cabeza"], 
     "respuesta": "Se hace con palma de coco y se coloca en la cabeza"},
    {"pregunta": "¿Cuál es el orden de los colores de la bandera de Colombia, de arriba hacia abajo?", 
     "opcion": ["Amarillo, Azul, Rojo", "Rojo, Azul, Amarillo", "Azul, Amarillo, Rojo", "Rojo, Amarillo, Azul"], 
     "respuesta": "Amarillo, Azul, Rojo"},
]
# ==========================
# HISTORIA
# ==========================
Historia = [
    {"pregunta": "¿Cómo se llama el personaje conocido como 'El Libertador'?", 
     "opcion": ["Simón Bolívar"," Francisco de Paula Santander", "Antonio Nariño", "José María Córdova"], 
     "respuesta": "Simón Bolívar"},
    {"pregunta": "¿Qué se celebra el 20 de julio?", 
     "opcion": ["la celebración de la paz mundial","El dia de la empanada","La independencia de Colombia","El día de la bandera"],
     "respuesta": "La independencia de Colombia"},
    {"pregunta": "¿Quién escribió Cien años de soledad?", 
     "opcion": ["Álvaro Cepeda Samudio","German Vargas","Mario Vargas Llosa","Gabriel García Márquez"], 
     "respuesta": "Gabriel García Márquez"},
    {"pregunta": "¿Qué premio Nobel ganó García Márquez?", 
     "opcion": ["Premio Nobel de Literatura","Premio Nobel de la Paz","Premio Nobel de Química","Premio Nobel de Física"], 
     "respuesta":"Premio Nobel de Literatura"},
    {"pregunta": "¿Qué fue la Guerra de los Mil Días?", 
     "opcion": ["Una guerra civil en Colombia","La violencia de la independencia","Una guerra entre Colombia y Venezuela","Un conflicto internacional en América del Sur"], 
     "respuesta": "Una guerra civil en Colombia"},
    {"pregunta": "¿Cuándo y en dónde murió Simón Bolívar?", 
     "opcion": ["Murió en 1830 en Santa Marta, Colombia", "Murió en 1820 en Bogotá, Colombia", "Murió en 1840 en Caracas, Venezuela", "Murió en 1850 en Lima, Perú"], 
     "respuesta": "Murió en 1830 en Santa Marta, Colombia"},
    {"pregunta": "¿Cuándo fue la batalla de Boyacá?", 
     "opcion": ["7 de agosto de 1819","7 de agosto de 1818","7 de agosto de 1820","6 de agosto de 1819"], 
     "respuesta": "7 de agosto de 1819"},
    
]
# ==========================
# NATURALEZA
# ==========================
Naturaleza = [
    {"pregunta": "¿Qué animal aparece en el escudo de Colombia?", 
     "opcion": ["El cóndor de los Andes", "Aguila real", "El águila calva", "El halcón peregrino"],
     "respuesta": "El cóndor de los Andes"},
    {"pregunta": "¿Qué animal vive colgado de los árboles de Colombia?", 
     "opcion": ["El perezoso", "El jaguar", "El oso perezoso", "El tapir"],
     "respuesta": "El oso perezoso"},
    {"pregunta": "¿Cuál es el animal más grande de la selva de Colombia?", 
     "opcion": ["El oso de lentes", "El jaguar", "El tapir", "El danta"],
     "respuesta": "El danta"},
    {"pregunta": "¿Qué ave rosada vive en la costa?", 
     "opcion": ["La espátula rosada", "El flamenco", "El ibis", "El tucán"],
     "respuesta": "El flamenco"},
    {"pregunta": "¿De qué fruto se produce el chocolate?", 
     "opcion": ["El maiz", "El café", "La vainilla", "El cacao"],
     "respuesta": "El cacao"},
    {"pregunta": "¿Cuál es el árbol nacional de Colombia?", 
        "opcion": ["La palma", "La palma de cera", "El pino", "El cedro"],
     "respuesta": "La palma de cera"},
    {"pregunta": "¿Cuál es la principal fuente de energía de Colombia?", 
     "opcion": ["La hidroeléctrica", "El carbón", "El petróleo", "El gas natural"],
     "respuesta": "La hidroeléctrica"},
    {"pregunta": "¿Qué mineral verde exporta Colombia?",
     "opcion": ["El rubí", "El diamante", "La esmeralda", "El zafiro"],
     "respuesta": "La esmeralda"},
    
]
